language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
script: grunt jasmine_node
before_install:
- openssl aes-256-cbc -K $encrypted_9690695c329b_key -iv $encrypted_9690695c329b_iv -in deploy/gramene_deploy_key2.enc -out deploy/gramene_deploy_key2 -d
after_success:
  - chmod 600 deploy/gramene_deploy_key2
  - scp -r -i deploy/gramene_deploy_key2 build images index.html mulvaney@brie.cshl.edu:test-deploy
addons:
  ssh_known_hosts: 
    - brie.cshl.edu
    - search.gramene.org