language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
script: grunt jasmine_node
before_install:
- openssl aes-256-cbc -K $encrypted_9690695c329b_key -iv $encrypted_9690695c329b_iv -in deploy/gramene_deploy_key2.enc -out deploy/gramene_deploy_key2 -d
after_success:
  - echo "Deploying build $TRAVIS_REPO_SLUG $TRAVIS_BRANCH (tag $TRAVIS_TAG isPullReq $TRAVIS_PULL_REQUEST) to production"
  - chmod 600 deploy/gramene_deploy_key2
  - scp -r -i deploy/gramene_deploy_key2 build images index.html mulvaney@brie.cshl.edu:test-deploy
  - ssh brie.cshl.edu "scp -i ~/.ssh/id_rsa_copy_to_gorgonzola -r test-deploy/* search.gramene.org:/usr/local/apache2/htdocs/gramene-search"
addons:
  ssh_known_hosts: 
    - brie.cshl.edu
    - search.gramene.org